FROM nciccbr/ccrgb_qctools:v1.4
ENV TAG="v1.5"

# TAG v1.0 has
# Fastqc v0.11.9
# picard tools v2.27.4

# TAG v1.1 has
# install multiqc 1.12

# TAG v1.2 has
# rseqc 4.0.0

# TAG v1.3 has
# htslib 1.15.1
# preseq 3.1.1

# TAG v1.4 has
# fastqvalidator 6d619a34749e9d33c34ef0d3e0e87324ca77f320

# TAG v1.5 has
# deeptools 3.5.1

# jellyfish
apt-get install -y jellyfish
# ADD http://www.cbcb.umd.edu/software/jellyfish/jellyfish-1.1.11.tar.gz /opt2
# WORKDIR /opt2
# RUN tar xjvf htslib-1.15.1.tar.bz2 && rm -f htslib-1.15.1.tar.bz2 && mkdir -p /opt2/htslib
# WORKDIR /opt2/htslib-1.15.1
# RUN ./configure && make && make install && cd /opt2 && rm -rf /opt2/htslib-1.15.1

# WORKDIR /opt2
# RUN tar xzvf jellyfish-1.1.11.tar.gz && rm -f jellyfish-1.1.11.tar.gz 
# WORKDIR /opt2/jellyfish-1.1.11 
# RUN ./configure && make && make install && cd /opt2 && rm -rf jellyfish-1.1.11
# kraken

# cleanup etc
COPY Dockerfile.${TAG} /opt2/Dockerfile.${TAG}
COPY printversions.bash /opt2/printversions
RUN if [ -f /opt2/Dockerfile ];then rm -f /opt2/Dockerfile;fi && \
    chmod a+r /opt2/Dockerfile.${TAG} && \
    ln -s Dockerfile.${TAG} /opt2/Dockerfile && \
    chmod a+rx /opt2/printversions
RUN /opt2/printversions > /opt2/versions.txt; exit 0
RUN chmod a+r /opt2/versions.txt
WORKDIR /data2
RUN apt-get clean && rm -rf /var/lib/apt/lists/*
http://www.cbcb.umd.edu/software/jellyfish/jellyfish-1.1.11.tar.gz