FROM nciccbr/ccrgb_qctools:v1.8.1
ENV TAG="v1.9"

# adding bedtools v2.22.0 required for hotspot plot generation 
# newer bedtools version is NOT giving the required output, hence older 
# version is required.

# add deconstructSigs R library
WORKDIR /opt2
RUN wget https://github.com/arq5x/bedtools2/releases/download/v2.22.0/bedtools-2.22.0.tar.gz && \
    tar xzvf bedtools-2.22.0.tar.gz && \
    rm -f bedtools-2.22.0.tar.gz
WORKDIR /opt2/bedtools2
RUN make
# now the bedtools v2.22.0 is at /opt2/bedtools2/bin/bedtools

# tagging
COPY Dockerfile.${TAG} /opt2/Dockerfile.${TAG}
COPY printversions.bash /opt2/printversions
RUN if [ -f /opt2/Dockerfile ];then rm -f /opt2/Dockerfile;fi && \
    chmod a+r /opt2/Dockerfile.${TAG} && \
    ln -s Dockerfile.${TAG} /opt2/Dockerfile && \
    chmod a+rx /opt2/printversions
RUN /opt2/printversions > /opt2/versions.txt; exit 0
RUN chmod a+r /opt2/versions.txt
WORKDIR /data2

# clean up
RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
    apt-get autoclean && \
    apt-get autoremove -y && \
    rm -rf /var/lib/{apt,dpkg,cache,log}/

# details
LABEL maintainer="vishal.koparde@nih.gov"
LABEL github_handle="kopardev"
ARG BUILD_DATE
LABEL build_date=$BUILD_DATE

