FROM nciccbr/ccbr_ubuntu_base_20.04:v2.0

# Fastqc
ADD https://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v0.11.9.zip /opt2/

WORKDIR /opt2
RUN unzip fastqc_v0.11.9.zip && \
    rm -f fastqc_v0.11.9.zip && \
    chmod 755 /opt2/FastQC/fastqc && \
    ln -s /opt2/FastQC/fastqc /usr/local/bin/fastqc

# cleanup etc
COPY Dockerfile /opt2/Dockerfile
COPY printversions.bash /opt2/printversions
RUN chmod a+rX /opt2/Dockerfile
WORKDIR /data2
RUN apt-get clean && rm -rf /var/lib/apt/lists/*