FROM nciccbr/ccrgb_qctools:v1.2
ENV TAG="v1.3"

# TAG v1.0 has
# Fastqc v0.11.9
# picard tools v2.27.4

# TAG v1.1 has
# install multiqc 1.12

# TAG v1.2 has
# rseqc 4.0.0

# preseq v2.0
ADD http://smithlabresearch.org/downloads/preseq_linux_v2.0.tar.bz2 /opt2
WORKDIR /opt2
RUN tar xjvf preseq_linux_v2.0.tar.bz2 && \
    mv preseq_linux_v2.0 preseq && chmod a+x preseq
ENV PATH="/opt2:$PATH"

# cleanup etc
COPY Dockerfile.${TAG} /opt2/Dockerfile.${TAG}
COPY printversions.bash /opt2/printversions
RUN if [ -f /opt2/Dockerfile ];then rm -f /opt2/Dockerfile;fi && \
    chmod a+r /opt2/Dockerfile.${TAG} && \
    ln -s Dockerfile.${TAG} /opt2/Dockerfile && \
    chmod a+rx /opt2/printversions
RUN /opt2/printversions > /opt2/versions.txt; exit 0
RUN chmod a+r /opt2/versions.txt
WORKDIR /data2
RUN apt-get clean && rm -rf /var/lib/apt/lists/*