FROM nciccbr/ccbr_ubuntu_base_20.04:v5

# build time variables
ARG BUILD_DATE="000000"
ENV BUILD_DATE=${BUILD_DATE}
ARG BUILD_TAG="000000"
ENV BUILD_TAG=${BUILD_TAG}
ARG REPONAME="000000"
ENV REPONAME=${REPONAME}

# Fastqc
ADD https://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v0.11.9.zip /opt2/
WORKDIR /opt2
RUN unzip fastqc_v0.11.9.zip && \
    rm -f fastqc_v0.11.9.zip && \
    chmod 755 /opt2/FastQC/fastqc && \
    ln -s /opt2/FastQC/fastqc /usr/local/bin/fastqc

# picard tools
ADD https://github.com/broadinstitute/picard/releases/download/2.27.4/picardcloud.jar /opt2
ENV PICARDJAR="/opt2/picardcloud.jar"
RUN chmod a+rX $PICARDJAR

# install multiqc
RUN pip3 install multiqc==1.14 RSeQC==5.0.1 deepTools==3.5.1

# htslib
ADD https://github.com/samtools/htslib/releases/download/1.15.1/htslib-1.15.1.tar.bz2 /opt2
WORKDIR /opt2
RUN tar xjvf htslib-1.15.1.tar.bz2 && rm -f htslib-1.15.1.tar.bz2 && mkdir -p /opt2/htslib
WORKDIR /opt2/htslib-1.15.1
RUN ./configure && make && make install && cd /opt2 && rm -rf /opt2/htslib-1.15.1

# preseq v2.0
ADD https://github.com/smithlabcode/preseq/releases/download/v3.1.2/preseq-3.1.2.tar.gz /opt2
WORKDIR /opt2
RUN tar -zxvf preseq-3.1.2.tar.gz && rm -f preseq-3.1.2.tar.gz && mkdir -p /opt2/preseq
WORKDIR /opt2/preseq-3.1.2
RUN ./configure --prefix=/opt2/preseq --enable-hts && make && make install && cd /opt2 && rm -rf /opt2/preseq-3.1.2
ENV PATH="/opt2/preseq/bin:$PATH"

# fastqvalidator
WORKDIR	/opt2
RUN	git clone https://github.com/statgen/fastQValidator.git
WORKDIR	/opt2/fastQValidator
RUN	export CXXFLAGS="-static-libgcc -static-libstdc++" && \
	export LD_FLAGS="-static -lpthread" && \
    git config --global url."https://github.com".insteadOf git://github.com && \
	make cloneLib && make
ENV	PATH="$PATH:/opt2/fastQValidator/bin"

# RNA-SeQC jar
ADD http://www.broadinstitute.org/cancer/cga/tools/rnaseqc/RNA-SeQC_v1.1.8.jar /opt2
ENV RNASEQCJAR="/opt2/RNA-SeQC_v1.1.8.jar"
RUN chmod a+rX $RNASEQCJAR

# rnaseqc new version 2.4.2
RUN mkdir -p /opt2/rnaseqc && \
  cd /opt2/rnaseqc && \
  wget https://github.com/getzlab/rnaseqc/releases/download/v2.4.2/rnaseqc.v2.4.2.linux.gz && \
  gzip -d rnaseqc.v2.4.2.linux.gz && \
  chmod a+x rnaseqc.v2.4.2.linux && \
  mv rnaseqc.v2.4.2.linux rnaseqc
ENV PATH="$PATH:/opt2/rnaseqc"

# adding R packages
# RUN Rscript -e 'install.packages("BiocManager")'
# RUN Rscript -e 'BiocManager::install("OmicCircos")'
# RUN Rscript -e 'BiocManager::install("copynumber")'
# RUN Rscript -e 'BiocManager::install("BSgenome")'
# RUN Rscript -e 'BiocManager::install("BSgenome.Hsapiens.UCSC.hg19")'
# RUN Rscript -e 'BiocManager::install("GenomeInfoDb")'

# RUN Rscript -e 'install.packages("stringr")'
# RUN Rscript -e 'install.packages("RColorBrewer")'
# RUN Rscript -e 'install.packages("optparse")'
# RUN Rscript -e 'install.packages("deconstructSigs")'
# RUN Rscript -e 'install.packages("sequenza")'
# RUN Rscript -e 'install.packages("reshape2")'
# RUN Rscript -e 'install.packages("grDevices")'
# RUN Rscript -e 'install.packages("graphics")'
# RUN Rscript -e 'install.packages("utils")'
# RUN Rscript -e 'install.packages("deconstructSigs")'
RUN Rscript -e 'install.packages("BiocManager")' && \
     Rscript -e 'BiocManager::install("OmicCircos")' && \
     Rscript -e 'BiocManager::install("copynumber")' && \
     Rscript -e 'BiocManager::install("BSgenome")' && \
     Rscript -e 'BiocManager::install("BSgenome.Hsapiens.UCSC.hg19")' && \
     Rscript -e 'BiocManager::install("GenomeInfoDb")'

RUN Rscript -e 'install.packages("stringr")' && \
     Rscript -e 'install.packages("RColorBrewer")' && \
     Rscript -e 'install.packages("optparse")' && \
     Rscript -e 'install.packages("deconstructSigs")' && \
     Rscript -e 'install.packages("sequenza")' && \
     Rscript -e 'install.packages("reshape2")' && \
     Rscript -e 'install.packages("grDevices")' && \
     Rscript -e 'install.packages("graphics")' && \
     Rscript -e 'install.packages("utils")' && \
     Rscript -e 'install.packages("deconstructSigs")'

# adding bedtools v2.22.0 required for hotspot plot generation 
# newer bedtools version is NOT giving the required output, hence older 
# version is required.

WORKDIR /opt2
RUN wget https://github.com/arq5x/bedtools2/releases/download/v2.22.0/bedtools-2.22.0.tar.gz && \
    tar xzvf bedtools-2.22.0.tar.gz && \
    rm -f bedtools-2.22.0.tar.gz
WORKDIR /opt2/bedtools2
RUN make
# now the bedtools v2.22.0 is at /opt2/bedtools2/bin/bedtools

# cleanup etc
# Save Dockerfile in the docker
COPY Dockerfile /opt2/Dockerfile_${REPONAME}.${BUILD_TAG}
RUN chmod a+r /opt2/Dockerfile_${REPONAME}.${BUILD_TAG}
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
    apt-get autoclean && \
    apt-get autoremove -y && \
    rm -rf /var/lib/{apt,dpkg,cache,log}/
WORKDIR /data2
