FROM nciccbr/ccrgb_qctools:v1.1
ENV TAG="v1.2"

# TAG v1.0 has
# Fastqc v0.11.9
# picard tools v2.27.4

# TAG v1.1 has
# install multiqc 1.12

# rseqc 4.0.0
WORKDIR /opt2
RUN wget https://sourceforge.net/projects/rseqc/files/RSeQC-4.0.0.tar.gz/download -O RSeQC-4.0.0.tar.gz && \
    tar xzvf RSeQC-4.0.0.tar.gz && rm -rf RSeQC-4.0.0.tar.gz
WORKDIR /opt2/RSeQC-4.0.0
RUN python setup.py install

# cleanup etc
COPY Dockerfile.${TAG} /opt2/Dockerfile.${TAG}
COPY printversions.bash /opt2/printversions
RUN if [ -f /opt2/Dockerfile ];then rm -f /opt2/Dockerfile;fi && \
    ln -s Dockerfile.${TAG} Dockerfile && \
    chmod a+r /opt2/Dockerfile.${TAG} && \
    chmod a+rx /opt2/printversions
RUN /opt2/printversions > /opt2/versions.txt; exit 0
RUN chmod a+r /opt2/versions.txt
WORKDIR /data2
RUN apt-get clean && rm -rf /var/lib/apt/lists/*