#!/bin/sh

prefix=`dirname $(readlink $0 || echo $0)`


java -Djava.awt.headless=true --module-path="${prefix}/lib" -Xmx${mem} \
  @"${prefix}/igv.args" \
  --module=org.igv/org.broad.igv.tools.IgvTools ${y[@]}
