FROM nciccbr/ccbr_ubuntu_base_20.04:v5

# build time variables
ARG BUILD_DATE="000000"
ENV BUILD_DATE=${BUILD_DATE}
ARG BUILD_TAG="000000"
ENV BUILD_TAG=${BUILD_TAG}
ARG REPONAME="000000"
ENV REPONAME=${REPONAME}

# get HLAminer
RUN cpanm -i --force Bio::SearchIO::blastxml
WORKDIR /opt2
RUN wget https://github.com/bcgsc/HLAminer/releases/download/v1.4/HLAminer_1-4.tar.gz && \
    tar xzvf HLAminer_1-4.tar.gz && \
    rm -f HLAminer_1-4.tar.gz && \
    for f in $(ls /opt2/HLAminer-1.4/HLAminer_v1.4/bin/*.sh);do echo $f;sed -i "s/..\/bin\//\/opt2\/HLAminer-1.4\/HLAminer_v1.4\/bin\//g" $f;sed -i "s/..\/database/\/opt2\/HLAminer-1.4\/HLAminer_v1.4\/database/g" $f; sed -i "s/-c ncbiBlastConfig.txt/-c \/opt2\/HLAminer-1.4\/HLAminer_v1.4\/bin\/ncbiBlastConfig.txt/g" $f; done && \
    for f in $(ls /opt2/HLAminer-1.4/HLAminer_v1.4/bin/*.pl);do echo $f;sed -i "s/..\/database/\/opt2\/HLAminer-1.4\/HLAminer_v1.4\/database/g" $f;sed -i "s/\/home\/martink\/bin\/perl/\/usr\/bin\/perl/g" $f;sed -i "s/\/home\/martink\/bin\/perl510/\/usr\/bin\/perl/g" $f;sed -i "s/\/usr\/bin\/perl510/\/usr\/bin\/perl/g" $f;done && \
    for f in $(ls /opt2/HLAminer-1.4/HLAminer_v1.4/bin/*.txt);do echo $f;sed -i "s/..\/bin\//\/opt2\/HLAminer-1.4\/HLAminer_v1.4\/bin\//g" $f;done
ENV PATH="$PATH:/opt2/HLAminer-1.4/HLAminer_v1.4/bin"
WORKDIR /opt2/HLAminer-1.4/HLAminer_v1.4/bin
COPY HPTASRrnaseq_classI-II.sh .
COPY HPTASRrnaseq_classI.sh .
COPY HPTASRwgs_classI-II.sh .
COPY HPTASRwgs_classI.sh .
RUN chmod a+x *.sh

# cleanup etc
# Save Dockerfile in the docker
COPY Dockerfile /opt2/Dockerfile_${REPONAME}.${BUILD_TAG}
RUN chmod a+r /opt2/Dockerfile_${REPONAME}.${BUILD_TAG}
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
    apt-get autoclean && \
    apt-get autoremove -y && \
    rm -rf /var/lib/{apt,dpkg,cache,log}/
WORKDIR /data2
