FROM nciccbr/ccbr_ubuntu_base_20.04:v1.4
ENV TAG="v1.0"

# install vdjtools
WORKDIR /opt2
RUN git clone https://github.com/mikessh/vdjtools.git && \
    cd vdjtools/ && \
    mvn clean install

# dependencies
# RUN apt-get update && \
#     apt-get -y install libcurl4-openssl-dev libxml2 libxml2-dev
# WORKDIR /opt2
# COPY dependencies.R /opt2
# RUN Rscript dependencies.R

# cleanup etc
COPY Dockerfile.${TAG} /opt2/Dockerfile.${TAG}
RUN chmod a+rX /opt2/Dockerfile.${TAG}
WORKDIR /data2
RUN apt-get clean

# details
LABEL maintainer="vishal.koparde@nih.gov"
LABEL github_handle="kopardev"
ARG BUILD_DATE
LABEL build_date=$BUILD_DATE