#!/bin/bash
# wrapper f
# Docker shells by default run as nonlogin, noninteractive
## It is insufficient to run `conda init bash` in a dockerfile, and then `source $HOME/.bashrc` in the entry script.
## This is mostly because the `RUN` directives are noninteractive, non-login shells, meaning `.bashrc` is never 
## sourced, and `RUN source` does not behave the way one might naively think it should
# using ideas from https://gist.github.com/xkortex/84226629c2a1286120bf139b93bca9bf

# This script will run as wrapper for mixcr
# it will create a subshell, activate the conda env mixcr and run mixcr before exiting the shell
__conda_setup="$('/opt2/conda/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
eval "$__conda_setup"
unset __conda_setup
conda activate mixcr
>&2 echo "USING mixcr CONDA env!... Please use the license found at s3://ccr-genomics-testdata/Licenses/mi.license"
exec mixcr $@
